services:
  - type: web
    name: laravel-ssp
    runtime: php
    buildCommand: "composer install && php artisan config:cache && php artisan route:cache && php artisan view:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: hopper.proxy.rlwy.net
      - key: DB_PORT
        value: 25037
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
